### ISSUE TITLE
Default factory not considered when setting defaults

### ISSUE THREAD

**Issue by KSneijders** [Divy1211/BinaryFileParser#7]
I just got an error when reading a file on the following line:

https://github.com/Divy1211/BinaryFileParser/blob/main/src/binary_file_parser/retrievers/Retriever.py#L165

Is that if statement correct? I have a feeling it maybe should be: 

```py
if self.default is None and self.default_factory is None:
```

**Comment by KSneijders** [comment]
@Divy1211 * bump * 🙂

**Comment by Divy1211** [comment]
[SFLR] Ahh yep, `default_factoty` was added later, looks like I missed a spot to update the conditions - will fix in a future release
